### ISSUE TITLE
Bar plot scaling issue

### ISSUE THREAD

**Issue by dv-usama-ansari** [datavisyn/visyn_core#116]
### Environment

 * Release number or git hash: 5.0.1
 * Browser: Chrome/Edge
 * Deployed / Local: local
---

### Steps to reproduce the bug

The Bar chart does not display visualizations of consistent size when multiples are selected

## Steps to reproduce
- Open the Basic Bar plot from the storybook
- Change the following values in the settings sidebar
   - Categorical Column: `category2`
   - Group: `value`
   - Multiples: `category`

## Observed Behavior
![image](https://github.com/datavisyn/visyn_core/assets/115616380/f0bef72e-cf08-45f1-b225-510026de3a00)

## Expected Behavior
All the bar plots should have a same height

**Comment by thinkh** [comment]
Fixed with #420.
