### ISSUE TITLE
scatter-vis: Show labels for selected items in scatter plot

### ISSUE THREAD

**Issue by dvchristianbors** [datavisyn/visyn_core#180]
## Short description

To facilitate using the scatter vis for presentation purposed, we shoult show the labels for items the user has selected

In order to prevent overplotting, we should introduce a maximum number of labels shown (e.g., 20, but this number likely needs to be determined during development).

## User stories

* As a *user*, I want to be able to see all labels for items that I are currently selected in the scatter vis, so that I can create a screenshot of the plot and use it to present value differences between my selections.
![image](https://github.com/datavisyn/visyn_core/assets/84898946/c3f5a7a1-fc09-4e1f-b1c5-a4b4161b70d1)

Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues 😃

**Comment by dv-raghad-jamalaldeen** [comment]
To address this we will use labeling as in the picture and provide three options (show all labels, show labels for selected items,  and hide labels)

![Screenshot from 2024-02-15 09-04-46](https://github.com/datavisyn/visyn_core/assets/143136267/9452e781-8d01-44f4-8849-fdfb4d13ebf6)
