### ISSUE TITLE
Download chart is clipped for long charts

### ISSUE THREAD

**Issue by thinkh** [datavisyn/visyn_core#479]
### Environment

 * Release number or git hash: 
 * Browser: 
 * Deployed / Local: 
---

### Steps to reproduce the bug

1. Open a bar chart that has scrollbars
2. Download the image

### Observed Behavior

The downloaded image is clipped.

![Bar chart (4)](https://github.com/user-attachments/assets/8bbbe6eb-f76f-40e9-8ba1-6f69444a9416)

### Expected Behavior

The downloaded image should not be clipped.

**Comment by thinkh** [comment]
Consider using/calling the https://echarts.apache.org/en/option.html#toolbox.feature.saveAsImage from echarts but be aware that we render individual plots for each facet.

**Comment by dv-usama-ansari** [comment]
- [ ] If not faceted, download the bar chart. no matter how long it is
- [ ] If faceted, download only what the user sees
- [ ] If faceted and a facet is focused, download it like unfaceted bar chart
