### ISSUE TITLE
Bar Chart follow up bugs

### ISSUE THREAD

**Issue by dv-usama-ansari** [datavisyn/visyn_core#563]
```[tasklist]
### Bugs which may be found after <https://github.com/datavisyn/visyn_core/pull/497> is merged
- [x] Improve performance by delegating resource heavy tasks to workers
- [x] Jumping of width after first render see https://github.com/datavisyn/visyn_core/issues/563#issuecomment-2416583243
- [x] Check if all the categorical columns are plotted correctly
- [x] Check if all the aggregations work as expected
- [x] Check if all the grouping types work as expected
- [x] Also check if grouping works correctly along with different combinations of categorical column and aggregations
- [x] Check the layout when the plot is grouped / stacked / normalized
- [x] Check the titles, axis labels, ticks, overflows and interactions
- [x] Check if all the facets work as expected
- [x] Check all of the above with facets enabled
- [x] Check for virtualization
- [x] Check if the preconfiguration is applied correctly
- [x] Check for responsiveness and behavior in tight spaces
- [x] Check if the download feature works as expected
- [x] Add playwright / jest tests
- [x] Sort the facets in ascending order and keep the unknown facet last
- [x] Handle all the bad values `null`, `undefined`, `Infinity`, `-Infinity`, `NaN` in data preprocessing
- [x] Show overlay or warning when no data (bad data filtered out resulting into no data)
- [x] Too many bars dont render - show a message
```

**Comment by dv-usama-ansari** [comment]
## Spacing between axis label and ticks
![563-axis-label-spacing](https://github.com/user-attachments/assets/0f91954d-964f-469b-9929-f65041032a87)

**Comment by dv-usama-ansari** [comment]
## Negative aggregation
![image](https://github.com/user-attachments/assets/933406f1-64bb-4588-8044-defe9705ef0f)

**Comment by dv-usama-ansari** [comment]
## Incorrect min and max values for axis
![image](https://github.com/user-attachments/assets/6bfb31ba-2e68-47c0-a973-04945d3f951f)

**Comment by dv-usama-ansari** [comment]
## Incorrect plotting for high median value

![image](https://github.com/user-attachments/assets/6ea03617-98b2-44eb-9661-ba2deeb31ed1)

**Comment by dv-usama-ansari** [comment]
## Overshooting median

![image](https://github.com/user-attachments/assets/5b85a0d4-cd2f-4977-bf67-a8b9c250d6f5)

**Comment by dv-usama-ansari** [comment]
## Clipped tooltip for very wide graph

![image](https://github.com/user-attachments/assets/659c00b4-44e2-41ab-8f1b-e7c22c62f4ba)

**Comment by dv-usama-ansari** [comment]
## Overshooting bars in stacked

![image](https://github.com/user-attachments/assets/81568871-5740-4483-85e5-a0776e4b7deb)

**Comment by dv-usama-ansari** [comment]
## Missing axis lines

![image](https://github.com/user-attachments/assets/47d58b38-35fb-4394-a3f3-89bac3792558)

**Comment by dv-usama-ansari** [comment]
## Incorrect binning

![image](https://github.com/user-attachments/assets/1102b7de-1f46-473e-aff4-92a3846acb63)

**Comment by dv-usama-ansari** [comment]
## Missing legend

![image](https://github.com/user-attachments/assets/88d91e5d-dbb5-4385-9828-91577595556a)

**Comment by dv-usama-ansari** [comment]
## Title clipped

![image](https://github.com/user-attachments/assets/0414b7a2-8565-441b-a901-26879370d942)

**Comment by dv-usama-ansari** [comment]
## Does not respect vertical space when there is only a single facet

**Comment by dv-usama-ansari** [comment]
## Should hide the aggregate axis labels when aggregate type is other than count

![image](https://github.com/user-attachments/assets/94dc69af-c559-471c-b6a4-cc988363ffd5)

**Comment by dv-usama-ansari** [comment]
## No coloring and wrong tooltip for single numerical grouping

![image](https://github.com/user-attachments/assets/532bef02-e67c-4c24-8a5c-d52aaa34b032)

**Comment by thinkh** [comment]
I noticed a jumping of the bar chart on first rendering. It first starts rather slim and with the next rerender has the full width. I'd expect that the bar chart is rendered with the full width already in the first render.

**Comment by dv-usama-ansari** [comment]
Bar plot group for a column containing all null values for [this session](https://ordino.dev.app.datavisyn.io/app/?session=dde75156-6138-4a31-9744-e2b071012eeb):

![Image](https://github.com/user-attachments/assets/7e1e2c3d-b0f7-4963-9d9e-a163307dd831)

Discussion with @thinkh: We should show `#71787E` Unknown item in the legend and the tooltip
