### ISSUE TITLE
Scatter plot: error with config value `regressionLineOptions: null`

### ISSUE THREAD

**Issue by thinkh** [datavisyn/visyn_core#578]
### Environment

 * Release number or git hash: v14.0.2
 * Browser: Chrome 130
 * Deployed / Local: local
---

### Steps to reproduce the bug

1. Use visualization config and run Ordino or Demo app

```json
{
    "alphaSliderVal": 0.5,
    "color": null,
    "dragMode": "select",
    "facets": null,
    "labelColumns": [],
    "numColorScaleType": "Sequential",
    "numColumnsSelected": [],
    "regressionLineOptions": null,
    "shape": null,
    "showLabelLimit": null,
    "showLabels": "Selected",
    "showLegend": null,
    "type": "Scatter plot"
}
```

### Observed Behavior

![Image](https://github.com/user-attachments/assets/e4e45bb6-1a26-44bb-a3d7-608ca890c59b)

The scatter plot does not render and points to these lines where the null check is missing:

https://github.com/datavisyn/visyn_core/blob/f67d209ffb1f1fc36fd43a8d347b4709c921c08c/src/vis/scatter/ScatterVis.tsx#L262-L265

I've tried to fix it like this:

```ts
    config.regressionLineOptions?.type,
    config.regressionLineOptions?.fitOptions,
    config.regressionLineOptions?.lineStyle,
    config.regressionLineOptions?.showStats,
```

However, that seems to be incomplete because the regression line options are incomplete in the sidebar.

![Image](https://github.com/user-attachments/assets/f097219b-3525-44b9-8a83-5295782c89c9)

I'd guess that merging the default values is missing somewhere.

### Expected Behavior

The scatterplot should also work correctly when passing `"regressionLineOptions": null`. Please also check the other optional config values. Thanks.

---

Thanks for taking the time to fill out this bug report 🤗
Make sure there aren't any open/closed issues for this topic 😃

**Comment by dvmoritzschoefl** [comment]
hey @thinkh I think this is intended. null is no valid value for regressionLineOptions (it is also typed this way). This is because default props merging will only work correctly with undefined values. ***null*** will actually override the default value (with null) while undefined/optional will not. So the solution would be to just use undefined/optional for this key.

example 
```
const obj = {};
console.log(merge(obj, { a: 'value', b: 'value' }, { a: undefined, b: null }));
// will print { a: 'value', b: null } 
```

**Comment by thinkh** [comment]
Thanks for the explanation. We discussed this together with @oltionchampari and agreed that we will fix it in Ordino for now. However, we also saw that the config typings are very confusing and mixed up. I created a follow-up issue https://github.com/datavisyn/visyn_core/issues/591 to fix the wrong typings.
